### ISSUE TITLE
Add an option to not generate the destinationJs: file

### ISSUE THREAD

**Issue by macta** [connected-world-services/metalsmith-simple-search#1]
If you are using a separate build tool like Brunch (or Webpack) its not so convenient to have simple-search create the jekyll search file for you, as instead you are more likely to let that external tool combine and minify your js files for you (to which I add the jeklyll search to that list). There isn't currently an option to NOT create the file, so you end up with something in your build directory that is unused.

It would be useful if setting an empty string for the filename, didn't create it (or don't provide a default, so that leaving it out means you don't get one).

As a workaround, i am using the metalsmith-ignore plugin to delete it in a later pipeline step.

**Comment by fidian** [comment]
Good idea!

**Comment by fidian** [comment]
Published version 1.2.0 with the option `skipSearchJs`. Set it to `true` and it won't generate the file.

**Comment by macta** [comment]
Works perfectly - thanks!
